# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eed14275d77240499820666ad55606aefeb4a1d24e9b195a09e4cb37e138aa9f061dd8d71df79ace237031d7d2be80eff4f417a7b70ce4b0ce7f3952fb8b34d

test:
  secret_key_base: 35e37f77439923c5073dde55b8f31f5079b28a4182b8f65f9aab26763ece6aca5f616d1d6004c4bc5bdcd50fe93884fb41c884475fa0f3d40ec2c56d28dca2e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
